config/routes.rb
Rails.application.routes.draw do
  root 'color_bits#index'
  get '/start', to: 'color_bits#start', :as => 'start'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/color_bits_controller.rb
class ColorBitsController < ApplicationController
  def index
    session[:rgb_tuple_queue] ||= []
    session[:rgb_tuple_queue] << random_rgb_tuple
  end

  def start
    @rgb_tuple = session[:rgb_tuple_queue].shift if session[:rgb_tuple_queue].present?
  end

  private

  def random_rgb_tuple
    "#{random_color_value}, #{random_color_value}, #{random_color_value}"
  end

  def random_color_value
    rand(0..255)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/color_bits/index.html.erb
<button id="color_bits">Start</button>

<script>
  $(document).ready(
      setInterval(function () {
        $.ajax({
          url: "<%= root_path %>",
          type: "GET",
          dataType: "script"
        });
      }, 3000)
  );

  $("#color_bits").click(function () {
    $("#color_bits").prop("disabled", true);
    setInterval(function () {
      $.ajax({
        url: "<%= start_path %>",
        type: "GET",
        dataType: "script"
      });
    }, 3000)
  });
</script>

app/views/color_bits/start.js.erb
<% if @rgb_tuple %>
  $(document).ready(function(){
    $("body").css("background-color", 'rgb(<%= @rgb_tuple %>)');
  });
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Littlebits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>